language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="0e44d7a8-b992-4dfd-bd9e-73a341c6c9a8"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - MKGumenyuk@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always